### ISSUE TITLE
Draw initial design for frontend app

### ISSUE THREAD

**Issue by kramstrom** [antoncarlsson/cloudnews#22]
In some app, like Figma

**Comment by kramstrom** [comment]
Two sketches of design:

normal view:
<img width="1440" alt="pop_up" src="https://user-images.githubusercontent.com/11044205/48130267-6144d580-e28c-11e8-8645-a7ad168cd921.png">

When a news-icon or item is clicked:
<img width="1440" alt="standard" src="https://user-images.githubusercontent.com/11044205/48130268-6144d580-e28c-11e8-84f3-5a95e7b03762.png">

Misc:
* font: Roboto

Colors:
* darkblue: 35495E
* green: 41B883
* lightgrey: E1E1E1
* darkgrey: 767676

**Comment by kramstrom** [comment]
Thoughts? @antoncarlsson @fsandelin @falapen @roca5461

**Comment by fsandelin** [comment]
😍😍✌✨✨

**Comment by antoncarlsson** [comment]
- Move the X to the top right and the arrow to the bottom right.
- Increase the size of the popup, at least vertically.
- Increase the left sidebar size and decrease the size of the area of the map, since Sweden is a very oblong country.
- Remove the right sidebar and move the buttons to the bottom right.

Otherwise, good job!
